### ISSUE TITLE
Please update to chai 1.10

### ISSUE THREAD

**Issue by DominikGuzei** [practicalmeteor/meteor-chai#3]
There are some improvements to assertion error display. Can you include the diff of object equality in tinytest?

**Comment by robot-lavaina** [comment]
Will do. Once I'm back from vacation. Send me ref to the diff stuff on how
to display it.

**Comment by DominikGuzei** [comment]
Cool thanks!
Here is the discussion about the object diffs: https://github.com/chaijs/chai/issues/106

**Comment by rbabayoff** [comment]
Updated to chai 2.1.0 in v2.1.0_1. Let me know if it works for you.
