### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by jgladch** [practicalmeteor/meteor-chai#4]
`Assertion.includeStack is deprecated, use chai.config.includeStack instead.`

**Comment by rbabayoff** [comment]
Hey, it's already changed in latest versions:

https://atmospherejs.com/practicalmeteor/chai

Please update to latest version.

**Comment by jgladch** [comment]
Maybe I'm missing something, but I just added the package today and am getting this error.

Using: `practicalmeteor:chai@1.9.2_3`

**Comment by rbabayoff** [comment]
it's an error or warning?

**Comment by jgladch** [comment]
Warning, apologies.

**Comment by rbabayoff** [comment]
No need to apologize :) I'll take a look at it anyway next time I update the chai version. It may also be coming from mocha, if you use the mocha package, since he also has chai included.

**Comment by jgladch** [comment]
Ah, I do have the mocha package installed, but this warning is coming from practicalmeteor_chai :)
